---
# tasks file for kibana
  - name: Upload tar.gz Kibana from local storage
    copy:
      src: "kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    register: get_kibana
    until: get_kibana is succeeded
    tags: kibana
  - name: Create directrory for Kibana
    become: true
    file:
      state: directory
      path: "{{ kibana_home }}"
    tags: kibana
  - name: Extract Kibana in the installation directory
    become: true
    unarchive:
      copy: false
      src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
      dest: "{{ kibana_home }}"
      extra_opts: [--strip-components=1]
      creates: "{{ kibana_home }}/bin/kibana"
    tags:
       - kibana
  - name: Set Kibana config
    become: true
    template:
      src: templates/kibana.yml.j2
      dest: "{{ kibana_home }}/config/kibana.yml"
    tags: kibana